build:
	g++ -Wall -IaBitmap example1.cpp aBitmap/aBitmap.cpp -o example1
	g++ -Wall -IaBitmap example2.cpp aBitmap/aBitmap.cpp -o example2

run:
	./example1
	./example2

clean:
	rm -r example1
	rm -r example2
	rm test*.bmp
